---
- name: Create database subnet group
  vars:
    db_sng_additional_tags:
      Name: "aap-infrastructure-{{ deployment_id }}-subnet-group"
    db_sng_tags: "{{ db_sng_additional_tags | combine(_infrastructure_tags) }}"
  amazon.aws.rds_subnet_group:
    region: "{{ infrastructure_region }}"
    state: present
    name: "aap-infrastructure-{{ deployment_id }}-subnet-group"
    description: Ansible Automation Platform Subnet Group
    subnets: "{{ infrastructure_subnet_ids }}"
    tags: "{{ db_sng_tags }}"
  register: infrastructure_db_subnet_group
  tags:
    - database

# AWS will only let us create one DB in the RDS instance, so we will need to create databases for Hub and EDA in later steps.
- name: Create RDS instance
  vars:
    db_additional_tags:
      Name: "aap-infrastructure-{{ deployment_id }}-db"
    db_tags: "{{ db_additional_tags | combine(_infrastructure_tags) }}"
  amazon.aws.rds_instance:
    region: "{{ infrastructure_region }}"
    id: "aap-infrastructure-{{ deployment_id }}-db"
    state: present
    engine: postgres
    db_name: controller
    engine_version: "{{ infrastructure_db_engine_version }}"
    allow_major_version_upgrade: "{{ infrastructure_db_allow_major_version_upgrade }}"
    auto_minor_version_upgrade: "{{ infrastructure_db_auto_minor_version_upgrade }}"
    multi_az: "{{ infrastructure_db_multi_az }}"
    storage_encrypted: "{{ infrastructure_db_storage_encrypted }}"
    db_instance_class: "{{ infrastructure_db_db_instance_class }}"
    username: "{{ infrastructure_db_username }}"
    password: "{{ infrastructure_db_password }}"
    storage_type: "{{ infrastructure_db_storage_type }}"
    iops: "{{ infrastructure_db_storage_iops | default(None) }}"
    allocated_storage: "{{ infrastructure_db_allocated_storage }}"
    vpc_security_group_ids:
      - "{{ infrastructure_security_group.group_id }}"
    db_subnet_group_name: "{{ infrastructure_db_subnet_group.subnet_group.name }}"
    tags: "{{ db_tags }}"
  tags:
    - database
  register: infrastructure_db
